#!/usr/bin/env python3
"""Generate a Mermaid mindmap page from the numbered documentation chapters."""

from __future__ import annotations

import html
from dataclasses import dataclass, field
from itertools import count
from pathlib import Path
import re

HEADING_RE = re.compile(r"^(#{1,3})\s+(?P<title>.+?)\s*$")
LINK_RE = re.compile(r"\[([^\]]+)\]\([^)]+\)")
CHAPTER_TITLE_RE = re.compile(r"^(?P<number>\d+)\s+")


@dataclass
class Section:
    """Structured representation of a heading and its nested subsections."""

    level: int
    title: str
    children: list["Section"] = field(default_factory=list)


def repo_root() -> Path:
    """Return the repository root."""
    return Path(__file__).resolve().parent.parent


def chapter_documents(docs_dir: Path) -> list[Path]:
    """Return the numbered chapter markdown files in sorted order."""
    return sorted(path for path in docs_dir.glob("[0-9][0-9]-*.md") if path.is_file())


def parse_chapter(path: Path) -> Section:
    """Parse a chapter markdown file into a nested H1/H2 heading tree."""
    sections: list[Section] = []

    for line in path.read_text(encoding="utf-8").splitlines():
        match = HEADING_RE.match(line)
        if match is None:
            continue
        level = len(match.group(1))
        if level > 2:
            continue
        sections.append(
            Section(
                level=level,
                title=" ".join(match.group("title").split()),
            )
        )

    if not sections:
        raise ValueError(f"No heading structure found in {path}")

    root = sections[0]
    stack = [root]

    for section in sections[1:]:
        while stack and stack[-1].level >= section.level:
            stack.pop()
        if not stack:
            raise ValueError(f"Invalid heading nesting in {path}")
        stack[-1].children.append(section)
        stack.append(section)

    return root


def chapter_number(section: Section) -> int:
    """Return the leading chapter number from a top-level chapter title."""
    match = CHAPTER_TITLE_RE.match(section.title)
    if match is None:
        raise ValueError(f"Chapter title does not start with a number: {section.title}")
    return int(match.group("number"))


def mermaid_label(text: str) -> str:
    """Return text safe for a Mermaid quoted node label."""
    plain = LINK_RE.sub(r"\1", text)
    return plain.replace('"', "'")


def emit_leaf(lines: list[str], indent: str, node_id: str, label: str) -> None:
    """Append a simple quoted Mermaid node."""
    lines.append(f'{indent}{node_id}["{mermaid_label(label)}"]')


def emit_section(
    section: Section,
    lines: list[str],
    indent: str,
    node_ids: count,
) -> None:
    """Render a section and its nested children as Mermaid mindmap nodes."""
    section_id = f"node_{next(node_ids):03d}"
    emit_leaf(lines, indent, section_id, section.title)

    child_indent = f"{indent}  "

    for child in section.children:
        emit_section(child, lines, child_indent, node_ids)


def render_mindmap(chapters: list[Section]) -> str:
    """Render the complete Mermaid mindmap."""
    flow_chapters = [chapter for chapter in chapters if chapter_number(chapter) <= 8]
    support_chapters = [chapter for chapter in chapters if chapter_number(chapter) >= 9]
    node_ids = count(1)

    lines = [
        "mindmap",
        '  root((S-CORE Infrastructure))',
        '    flow["Engineering Flow"]',
    ]

    for chapter in flow_chapters:
        emit_section(chapter, lines, "      ", node_ids)

    lines.append('    support["Supporting Layers"]')
    for chapter in support_chapters:
        emit_section(chapter, lines, "      ", node_ids)

    return "\n".join(lines)


def render_page(chapters: list[Section]) -> str:
    """Return the markdown page that hosts the Mermaid mindmap."""
    diagram = html.escape(render_mindmap(chapters))

    return "\n".join(
        [
            "<!-- Generated by scripts/generate_mindmap.py. Do not edit manually. -->",
            "",
            "# Infrastructure Mindmap",
            "",
            "This page turns the numbered infrastructure chapters into one large Mermaid mindmap.",
            "",
            "It is generated straight from the `#` and `##` headings in the numbered chapter files.",
            "Run `python3 scripts/generate_mindmap.py` after changing the chapter structure.",
            "",
            '<p class="mindmap-note">The map is intentionally limited to chapter and section level for readability.</p>',
            "",
            '<div class="mindmap-shell">',
            '<div class="mermaid">',
            diagram,
            "</div>",
            "</div>",
            "",
        ]
    )


def main() -> int:
    """Generate the docs mindmap page and return a shell-friendly exit code."""
    docs_dir = repo_root() / "docs"
    output_path = docs_dir / "mindmap.md"

    chapters = [parse_chapter(path) for path in chapter_documents(docs_dir)]
    output_path.write_text(render_page(chapters), encoding="utf-8")
    print(f"Updated {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
