#!/usr/bin/env python3
"""Generate a Mermaid mindmap page from the numbered documentation chapters."""

from __future__ import annotations

import html
from dataclasses import dataclass, field
from itertools import count
from pathlib import Path
import re
import textwrap

HEADING_RE = re.compile(r"^(#{1,3})\s+(?P<title>.+?)\s*$")
LINK_RE = re.compile(r"\[([^\]]+)\]\([^)]+\)")


@dataclass
class Section:
    """Structured representation of a heading and its nested subsections."""

    level: int
    title: str
    children: list["Section"] = field(default_factory=list)


def repo_root() -> Path:
    """Return the repository root."""
    return Path(__file__).resolve().parent.parent


def chapter_documents(docs_dir: Path) -> list[Path]:
    """Return the numbered chapter markdown files in sorted order."""
    return sorted(path for path in docs_dir.glob("[0-9][0-9]-*.md") if path.is_file())


def wrap_label(text: str, width: int) -> str:
    """Return text wrapped with Mermaid-friendly HTML line breaks."""
    lines = textwrap.wrap(
        text,
        width=width,
        break_long_words=False,
        break_on_hyphens=True,
    )
    return "<br/>".join(lines) if lines else text


def display_title(section: Section) -> str:
    """Return a wrapped label while preserving the original heading text."""
    title = LINK_RE.sub(r"\1", section.title)
    if section.level == 1:
        return wrap_label(title, width=22)
    return wrap_label(title, width=24)


def parse_chapter(path: Path) -> Section:
    """Parse a chapter markdown file into a nested H1/H2 heading tree."""
    sections: list[Section] = []

    for line in path.read_text(encoding="utf-8").splitlines():
        match = HEADING_RE.match(line)
        if match is None:
            continue
        level = len(match.group(1))
        if level > 2:
            continue
        sections.append(
            Section(
                level=level,
                title=" ".join(match.group("title").split()),
            )
        )

    if not sections:
        raise ValueError(f"No heading structure found in {path}")

    root = sections[0]
    stack = [root]

    for section in sections[1:]:
        while stack and stack[-1].level >= section.level:
            stack.pop()
        if not stack:
            raise ValueError(f"Invalid heading nesting in {path}")
        stack[-1].children.append(section)
        stack.append(section)

    return root


def mermaid_label(text: str) -> str:
    """Return text safe for a Mermaid quoted node label."""
    plain = LINK_RE.sub(r"\1", text)
    return plain.replace('"', "'")


def emit_leaf(
    lines: list[str],
    indent: str,
    node_id: str,
    label: str,
) -> None:
    """Append a simple quoted Mermaid node."""
    lines.append(f'{indent}{node_id}["{mermaid_label(label)}"]')


def emit_section(
    section: Section,
    lines: list[str],
    indent: str,
    node_ids: count,
) -> None:
    """Render a section and its nested children as Mermaid mindmap nodes."""
    section_id = f"node_{next(node_ids):03d}"
    emit_leaf(lines, indent, section_id, display_title(section))

    child_indent = f"{indent}  "

    for child in section.children:
        emit_section(child, lines, child_indent, node_ids)


def render_mindmap(chapters: list[Section]) -> str:
    """Render the complete Mermaid mindmap."""
    node_ids = count(1)

    lines = [
        "%%{init: {'themeVariables': {'fontSize': '16px'}}}%%",
        "mindmap",
        '  root((S-CORE Infrastructure))',
    ]

    for chapter in chapters:
        emit_section(chapter, lines, "      ", node_ids)

    return "\n".join(lines)


def render_page(chapters: list[Section]) -> str:
    """Return the markdown page that hosts the Mermaid mindmap."""
    diagram = html.escape(render_mindmap(chapters))

    return "\n".join(
        [
            "<!-- Generated by scripts/generate_mindmap.py. Do not edit manually. -->",
            "",
            "# Infrastructure Mindmap",
            "",
            "This page turns the numbered infrastructure chapters into one large Mermaid mindmap.",
            "",
            "It is generated straight from the `#` and `##` headings in the numbered chapter files.",
            "Run `python3 scripts/generate_mindmap.py` after changing the chapter structure.",
            "",
            '<p class="mindmap-note">Titles are unchanged; only line breaks and hierarchy styling are used to improve readability.</p>',
            "",
            '<div class="mindmap-shell">',
            '<div class="mermaid">',
            diagram,
            "</div>",
            "</div>",
            "",
        ]
    )


def main() -> int:
    """Generate the docs mindmap page and return a shell-friendly exit code."""
    docs_dir = repo_root() / "docs"
    output_path = docs_dir / "mindmap.md"

    chapters = [parse_chapter(path) for path in chapter_documents(docs_dir)]
    output_path.write_text(render_page(chapters), encoding="utf-8")
    print(f"Updated {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
